version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pg_datamypr
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/dbdata:/var/lib/postgresql/data/pg_datamypr
    networks:
      - app_network
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - app
      - front
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app_network
  front:
    image: httpd:latest
    volumes:
      - ./front:/usr/local/apache2/htdocs
    networks:
      - app_network
  app:
    image: python
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      DB_HOST: postgres
      DB_NAME: postgres_db
      DB_USER: postgres
      DB_PASSWORD: qwerty
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    depends_on:
      - postgres
    networks:
      - app_network
networks:
  app_network:
    driver: bridge















